token = ""
owners = [ 141231597155385344, ]
dm_uncaught_errors = false
support_guild_id = 208895639164026880
bot_support_role_id = 522072743273824262

[event_webhook]
    event_webhook_url = ""
    [event_webhook.events]
        guild_join = false
        guild_remove = false
        shard_connect = false
        shard_disconnect = false
        shard_ready = false
        bot_ready = false
        unhandled_error = true

[intents]
    guilds = true  # Guilds - recommended: true. Used for guild join/remove, channel create/delete/update, Bot.get_channel, Bot.guilds.
    members = false  # Members - recommended: false (privileged intent). Used for member join/remove/update, Member.roles, Member.nick, User.name, etc.
    bans = false  # Bans - recommended: false. Used for member ban/unban.
    emojis = false  # Emojis - recommended: false. Used for guild emojis update, Bot.get_emoji, Guild.emojis.
    integrations = false  # Integrations - recommended: false. Used for guild integrations update.
    webhooks = false  # Webhooks - recommended: false. Used for guild webhooks update.
    invites = false  # Invites - recommended: false. Used for invite create/delete.
    voice_states = false  # Voice states - recommended: false. Used for voice state update, VoiceChannel.members, Member.voice.
    presences = false  # Presences - recommended: false (privileged intent). Used for member update (for activities and status), Member.status.
    guild_messages = true  # Guild messages - recommended: true. Used for message events in guilds.
    dm_messages = false  # DM messages - recommended: true. Used for message events in DMs.
    guild_reactions = false  # Guild reactions - recommended: false. Used for [raw] reaction add/remove/clear events in guilds.
    dm_reactions = false  # DM reactions - recommended: false. Used for [raw] reaction add/remove/clear events in DMs.
    guild_typing = false  # Guild typing - recommended: false. Used for the typing event in guilds.
    dm_typing = false  # DM typing - recommended: false. Used for the typing event in Dms.

[bot_listing_api_keys]
    topgg_token = ""  # The token used to post data to top.gg
    discordbotlist_token = ""  # The token used to post data to discordbotlist.com

[bot_info]
    enabled = true
    include_stats = true
    content = """Flower is a cute lil bot for growing and taking care of flowers. Discord can be a scary place, so it's nice to always have a flower garden for you to come back home to~ :3"""

    links.Website.url = "https://voxelfox.co.uk"
    links."Support Server".url = "https://discord.gg/vfl"
    links.Git.url = "https://github.com/Voxel-Fox-Ltd/Flower/"
    links.Premium.url = "https://voxelfox.co.uk/portal/flower"
    links.Vote.url = "https://top.gg/bot/731736201400418314/vote"
    links.Review.url = "https://top.gg/bot/731736201400418314#reviews"

[database]
    user = ""
    password = ""
    database = ""
    host = ""
    port = 20184
    enabled = true

[embed]
    enabled = false
    content = ""
    colour = 0
    [embed.author]
        enabled = false
        name = "{ctx.bot.user}"
        url = ""
    embed.footer = [
        {amount = 1, text = "Add the bot to your server! ({ctx.clean_prefix}invite)"},
        {amount = 1, text = "Vote for Flower on Top.gg and get an exp multiplier! ({ctx.clean_prefix}vote)"},
        {amount = 1, text = "Water your plants from the website! ({ctx.clean_prefix}website)"},
        {amount = 3, text = "You can get more than 5 plants by subscribing! ({ctx.clean_prefix}donate)"},
        {amount = 3, text = "Did you know you can see all of your plants at once? ({ctx.clean_prefix}showall)"},
        {amount = 3, text = "Subscribe to the bot and get an exp multiplier! ({ctx.clean_prefix}donate)"},
        {amount = 3, text = "Change your pot colour by subscribing! ({ctx.clean_prefix}donate)"},
    ]

[presence]
    activity_type = "watching"
    text = "the bees fly"
    status = "online"
    include_shard_id = true
    [presence.streaming]
        twitch_usernames = [ "", ]
        twitch_client_id = ""  # https://dev.twitch.tv/console/apps
        twitch_client_secret = ""

[oauth]
    enabled = true
    client_id = "731736201400418314"
    scope = "bot applications.commands"
    permissions = [
        "send_messages",
        "attach_files",
        "embed_links",
    ]

[statsd]
    host = "127.0.0.1"
    port = 8125
    constant_tags.service = "Flower"
