token = "bot_token"
topgg_token = ""
owners = [ 141231597155385344, ]  # The first should always be the developer
dm_uncaught_errors = false
default_prefix = "p."  # The prefix for the bot's commands
event_webhook_url = ""

# Data that's copied directly over to a command without processing
[command_data]
    guild_invite = "https://discord.gg/vfl"
    github = "https://github.com/4Kaylum/Flower"
    patreon = ""
    invite_command_enabled = true
    echo_command_enabled = true
    stats_command_enabled = true
    vote_command_enabled = true

# This data is passed directly over to asyncpg
[database]
    user = "database_username"
    password = "database_password"
    database = "database_name"
    host = "127.0.0.1"
    port = 5432
    enabled = false

# This data is passed directly over to aioredis
[redis]
    host = "127.0.0.1"
    port = 6379
    db = 0
    enabled = false

# What the bot is playing
[presence]
    activity_type = "playing"  # Should be one of 'playing', 'listening', 'watching'
    text = "Game playing text"
    status = "online"  # Should be one of 'online', 'invisible', 'idle', 'dnd'

# Used to generate the invite link - client ID only necessary for webserver
[oauth]
    client_id = ""
    client_secret = ""

# This is where you can set up all of your analytics to be sent to GA
[google_analytics]
    tracking_id = ""  # Tracking ID for your GA instance
    app_name = ""  # The name of your bot - what you want GA to name this traffic source
    document_host = ""  # The (possibly fake) URL you want to tell GA this website is
